### ISSUE TITLE
gridle.js Issues

### ISSUE THREAD

**Issue by dodozhang21** [olivierbossel/gridle#42]
Hi,

I'm trying to bundle your gridle.js e.g.

concat: {
            options: {
                stripBanners: true
            },
            foot: {
                src: [
                    'bower_components/gridle/js/gridle.js',
                    'bower_components/gridle/js/gridle.js.map',
                    'bower_components/masonry/dist/masonry.pkgd.js',
                    'js/*.js'
                ],
                dest: 'bundles/js/foot.js'
            }
        }

But when I include 'foot.js' on my site, I get:

 GET http://localhost:1234/work/gridle/bundles/js/gridle.js.map 404 (Not Found)

If I include gridle.js without bundling, it works.  But we'd like to bundle all of our js for performance.

Is there a fix for this?

**Comment by dodozhang21** [comment]
Hi,

I have another issue with Gridle.js.  As soon as I replaced the original css with a minified version of it the Gridle.js can no longer detect registered states. I verified that #gridle-settings is in my minified css file.  Could you tell me what else the js is looking for to work properly?

Here's what I'm doing to minify it. Via grunt-contrib-cssmin

cssmin: {
		  target: {
			files: [{
			  expand: true,
			  cwd: 'css',
			  src: ['*.css', '!*.min.css'],
			  dest: 'css-min',
			  ext: '.min.css'
			}]
              ,
            options: {
                shorthandCompacting: false
            }
		  }
		}

I want to minify my css but would like Gridle.js to function as usual.

**Comment by olivierbossel** [comment]
Hi,

the first "issue" isn't really one. The coffee file in the repo is integrating the sourceMappingURL directive, this is why your browser try to fetch the sourcemap file. In order to fix this, you can update your gridle version to the latest one and simply grab the gridle.min.js file instead of the gridle.js one... You can also remove the gridle.js.map file from your build..

The second issue is now fixed normally. There was an issue with the regexp that grab the states from the css file. Now it should be ok..

Let me know!

Cheers!

**Comment by lauterry** [comment]
Hi @olivierbossel 

I still encountered the issue where gridle.js didn't find #gridle-settings in my minified styles.

```
if (this._statesInCss) {   <----- nulll
        return this._processFindedStates();
 }
```

I search for "#gridle-settings" in my minified css but didn't found it.

I'm using gridle v2.0.46.

What the problem would be ?

Best regards
